account/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

app_name = 'mysite'


urlpatterns = [
    
    path('', views.index, name='home'),
    # path('landing/', views.landing, ),  # Materializeを使用したトップページ

    path('login/', views.Login.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),

    path('mypage/', views.MyPageView.as_view(), name='mypage'),
    path('favorite/', views.favorite, name='favorite'),
    path('contact/', views.ContactView.as_view(), name='contact'),

    path('about/', views.about, name='about'),

]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'


urlpatterns = [
    # slug:pkとすることで、'localhost:8000/blog/~'の"~"に入ったものを変数pkとして使用できる
    # （slugの他、int=整数のみ, str=文字列のみがある）
    path("<int:pk>/", views.article, name="article"),
    path("tags/<slug:slug>/", views.tags, name="tags"),
    path("", views.blog, name="blog"),
    path('<slug:pk>/like/', views.like),
    path('<slug:pk>/fav/', views.add_favorite),
    path('add/', views.add_post, name='add'),
    path('edit/<int:pk>', views.edit_post, name='edit'),
    path('delete/<int:pk>/', views.delete_post, name="delete"),
    path('my_posts/', views.my_posts, name='my_posts'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', include('account.urls')),
]
# + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser

class UserManager(BaseUserManager):

    def create_user(self, email, password=None):
        if not email:
            raise ValueError('Users must have an email address')
        user = self.model(
            email=self.normalize_email(email),
        )
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_superuser(self, email, password=None):
        user = self.create_user(
            email,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):   # AbstractUserより柔軟性あり
    email = models.EmailField(
        max_length=255,
        unique=True,
    )
    is_active = models.BooleanField(default=True)   # アカウントが有効か
    is_admin = models.BooleanField(default=False)   # 管理画面に入れるか

    objects = UserManager()

    USERNAME_FIELD = 'email'    # usernameをemailにする
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        'Does the user have a specific permission?'
        return True

    def has_module_perms(self, app_label):
        'Does the user have permissions to view the app "app_label"?'
        return True
    
    @property
    def is_staff(self):
        'Is the user a member of staff?'
        return self.is_admin

# ----- OneToOneField を同時に作成 -----
from django.db.models.signals import post_save
from django.dispatch import receiver

@receiver(post_save, sender=User)   # post_save(=Userを保存した直後)に、sender=Userでreceiver=Profileで下の処理を追加
def create_onetoone(sender, **kwargs):
    if kwargs['created']:
        Profile.objects.create(user=kwargs['instance']) # Profileモデルのuserフィールド=kwargs['instance']
# ----- OneToOneField を同時に作成 -----



from django.db import models
from django.contrib.auth import get_user_model
import os

# instance, filenameを使用して、パスを生成する
def upload_image_to(instance, filename):
    user_id = str(instance.user.id)
    return os.path.join('image', user_id, filename)


class Profile(models.Model):    
    # Userが作成された時に、Profileも作成する⇨account_modelsのcreate_onetoone関数部分参照
    user = models.OneToOneField(    # user: profile = 1 : 1
        get_user_model(),
        unique=True,
        on_delete=models.CASCADE,
        primary_key=True        # userをそのままidにする
    )
    username = models.CharField(
        default="Anonymous",
        max_length=30,
    )
    country = models.CharField(
        default="",
        max_length=50,  
    )
    city = models.CharField(
        default="",
        blank=True,
        null=True,
        max_length=50,
    )
    age = models.PositiveIntegerField(
        blank=True,
        null=True,
    )
    hobby = models.CharField(
        max_length=100,
        default='',
        blank=True,
        null=True,
    )
    image = models.ImageField(
        default="",
        blank=True,
        upload_to=upload_image_to,
    )
    def __str__(self):
        return f'{self.username}'

blog/models.py
from django.db import models
import os
from account.models import Profile

class Tag(models.Model):
    slug = models.CharField(    # slug: 半角文字
        primary_key=True,   # slug = id として扱える
        unique=True,
        max_length=20,
    )
    name = models.CharField(
        unique=True,
        max_length=20,
    )
    class Meta:
        ordering = ("slug", ) # slugで昇順ソート

    def __str__(self):
        return self.slug


def upload_blogimage_to(instance, filename):
    return os.path.join('image', 'blog', filename)

class Article(models.Model):
    title = models.CharField(
        max_length=30, 
        default="",
    )
    text = models.TextField(
        default="",
    )
    author = models.ForeignKey(
        Profile,
        on_delete=models.CASCADE,
        default='1'
    )
    created_at = models.DateField(
        auto_now_add=True, 
    )
    updated_at = models.DateField(
        auto_now=True, 
    )
    like_count = models.IntegerField(
       default=0,
    )
    tags = models.ManyToManyField(
        Tag,
        blank=True,
    )
    image = models.ImageField(
        upload_to = upload_blogimage_to,
        default="",
        blank=True,
    )
    favorite = models.ManyToManyField(
        Profile,
        related_name='favorite_by',
        blank=True,
    )
    is_published = models.BooleanField(
        default=False,
    )

    def __str__(self):
        return self.title


class Comment(models.Model):

    comment = models.TextField(
        default="", 
        max_length=500, 
    )
    created_at = models.DateField(
        auto_now_add=True, 
    )
    user = models.ForeignKey(
        Profile, 
        on_delete=models.CASCADE    # Userがいなくなったら、そのコメントは削除
    )    
    article = models.ForeignKey(
        Article, 
        on_delete=models.CASCADE    # 記事がなくなったら、そのコメントは削除
    )

templates/mysite/about.html
{% extends 'mysite/base.html' %}
{% load static %}
{% block content %}
 

<main class="container">
    <div class="row">
        <div class="col-md-8">
            <h3 class="pb-2 mb-4" style="font-family: 'Raleway', sans-serif; font-size: 30px; border-bottom-style: groove; border-bottom-color: rgba(255, 255, 255, .6);">About</h3>

            <img src='{% static "mysite/about.jpg" %}' style='width: 100%;'>
            <div class='my-2 py-2'>
                <p style='font-size: 18px;'>You can share your experiences, memories with people from all over the world!! <br><br>
                <strong>We all are travellers. </strong>Even if it feels like a trivial daily scene to you, it will be possibly different to people with other cultural backgrounds.<br><br>
                Through living in three countries, I had some cross-cultural experiences. Some cultures seemed interesting and great, but some seemed shocked and unacceptable. 
                These experiences helped me to see my cultures objectively. <br><br>

                I'm Japanese, and when I stayed in Mexico, I was surprised at the difference in the sense of time. In my country, trains and buses run almost on time, but they don't there.
                When I started my stay, I was always frustrated. However as I gradually got used to life and got along with the locals, I began to think like this...  <br><br>
                "If the bus comes on time, I'm lucky today!!" <br>In other words, <strong>I changed my mind positively and didn't take things for granted. </strong><br><br>
                Of course, we don't think exactly the same, even if they have the same roots. So I often felt a difference in thinking even though I'm in Japan. <br>
                But in order to understand each other, we should try to know the other fist. 
                <br><br>
                Communicating your thoughts and feelings leads to create or at least to make closer to the world where everyone can understand each other. <br><br>
                So please share your experiences here and find something awesome too!! 
                </p>
            </div>
        </div>

        {% include 'mysite/snippets/sidebar.html' %}

    </div>

</main>


{% endblock %}

templates/mysite/add_post.html
{% extends 'mysite/base.html' %}
{% load static %}
{% block content %}
 

<main class="container">
    <div class="row">
        <div class="col-md-8">
            <h3 class="pb-2 mb-4" style="font-family: 'Raleway', sans-serif; font-size: 30px; border-bottom-style: groove; border-bottom-color: rgba(255, 255, 255, .6);">{% if 'add' in request.path %}New{% else %}Edit{% endif%} Post</h3>

            <form method='POST' action={% if 'add' in request.path %}'{% url "blog:add" %}'{% else %}'{% url "blog:edit" article.id %}'{% endif %} style='margin:15px;' enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <input type='submit' value='{% if "add" in request.path %}投稿{% else %}更新{% endif %}' />
            </form>

        </div>

        {% include 'mysite/snippets/sidebar.html' %}

    </div>

</main>


{% endblock %}

templates/mysite/auth.html
{% extends 'mysite/base_auth.html' %}

{% block content %}

<div class="container">
    <div class="row">
        
        <div class="col-lg-3 m-auto">
            <h1 class="display-4 text-center" style="font-family: 'Raleway', sans-serif;">
                <a href="{% url 'mysite:home' %}" class="text-decoration-none">Find Awesome</a>
            </h1>
        </div>

        <div class="col-lg-3 m-auto">

            <form class="form-signin mx-4" method="POST">
                {% csrf_token %}
                <div class="text-center">

                    <h1 class="h5 my-4">
                        {% if 'login' in request.path %}
                        Login
                        {% elif 'signup' in request.path %}
                        SignUp
                        {% endif %}
                    </h1>
                
                </div>

                <div class="form-label-group my-3">
                    <input type="email" id="id_email" name="{% if 'login' in request.path %}username{% elif 'signup' in request.path %}email{% endif %}" class="form-control" placeholder="Email address" required autofocus>
                </div>

                <div class="form-label-group my-3">
                    <input type="password" id="id_password" name="password" class="form-control" placeholder="Password" required>
                </div>

                <button class="btn btn-primary btn-block my-3" type="submit">Sign in</button>

            </form>

            {% if 'login' in request.path %}
            <div class="text-center">
                <a href="{% url 'mysite:signup' %}" class="link-secondary">Click here to Register</a>
            </div>
            {% elif 'signup' in request.path %}
            <div class="text-center">
                <a href="{% url 'mysite:login' %}" class="link-secondary">Click here to Login</a>
            </div>
            {% endif %}


        </div>

    </div>
</div>

{% endblock %}

templates/mysite/base.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    {% include 'mysite/snippets/head.html' %}

  </head>
  <body>

    {% include 'mysite/snippets/header.html' %}
    {% include 'mysite/snippets/messages.html' %}


    {% block content %}
    {% endblock %}

    {% include 'mysite/snippets/footer.html' %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  </body>
</html>

templates/mysite/base_auth.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    {% include 'mysite/snippets/head.html' %}
  </head>

  <body class="vh-100 d-flex align-items-center justify-content-center bg-light">

    {% block content %}
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  </body>
</html>

templates/mysite/cache_test.html
Result：{{ answer }}

templates/mysite/cache_test3.html
{% load cache %}

キャッシュなし：{{ time }}
<br><br>
{% cache 30 first_cache %}

<p>-----この中に記載したもののみキャッシュされます-----</p>
キャッシュあり：{{ time }}　 
※ 30秒間は更新しても同じ秒表示のまま
<p>---------------------------------------------</p>

{% endcache %}



{% cache 40 second_cache request.user %}

" cache 秒数 キャッシュ名 + 変数 " とすることで、任意の値がurlに入ったGETごとにキャッシュをするか判断してくれる

{% endcache %}

templates/mysite/contact.html
{% extends 'mysite/base.html' %}
 
{% block content %}
 
<main class="container">
    <div class="row">
        <div class="col-md-8">
        <h3 class="pb-3 mb-4" style="font-family: 'Raleway', sans-serif; font-size: 30px; border-bottom-style: groove; border-bottom-color: rgba(255, 255, 255, .6);">
            Contact
        </h3>
 
        <form class="row g-3" method="POST">
            {% csrf_token %}
            <div class="col-12">
                <label class="form-label">Name</label>
                <input type="text" class="form-control" id="id_name" name="name" placeholder="" required>
            </div>

            <div class="col-12">
                <label class="form-label">Email address</label>
                <input type="email" class="form-control" id="id_email" name="email" required>
            </div>

            <div class="col-12">
                <label class="form-label">Inquiry</label>
                <textarea class="form-control" name="content" rows="4" required></textarea>
            </div>

            {% include 'mysite/snippets/grecaptcha.html' %}


            <div class="col-12">
                <button type="submit" id="submit" class="btn btn-primary" disabled>Submit</button>
            </div>

          </form>
 
        </div>
 
        {% include 'mysite/snippets/sidebar.html' %}
 
    </div>
</main>
 
 
{% endblock %}

templates/mysite/favorite.html
{% extends 'mysite/base.html' %}
{% block content %}
 
 {% load static %}
<main class="container">
    <div class="row">
        <div class="col-md-8">
            <h3 class="pb-4 mb-4 font-italic border-bottom">
                Favorite
            </h3>


                {% for article in articles %}
                <div class="col-11 mb-4 rounded">

                <a href="{% url 'blog:article' article.id %}" class="text-decoration-none link-secondary">
                    <div class="blog-post">
                        <h2 class="blog-post-title">{{ article.title }}</h2>

                        <p class="blog-post-meta">{{ article.created_at|date:"Y-m-j" }}  by <a href="#">{{ article.author }}</a></p>
                        {% for tag in article.tags.all %}
                            # {{ tag }}　
                        {% endfor %}
                    </div>
                </a>

                <hr>
                </div>
                {% endfor %}



            
        </div>

 
        {% include 'mysite/snippets/sidebar.html' %}
 
    </div>
</main>
 
 
{% endblock %}

templates/mysite/index.html
{% extends 'mysite/base.html' %}
{% load static %}
{% block content %}

<div class="container">
    <div class="p-4 p-md-6 p-8 mb-4 rounded img-fluid bg-dark">
    {% comment %} <div class="p-4 p-md-6 p-8 mb-4 rounded img-fluid" style='background-image: url("/static/mysite/memory02.jpg"); opacity: 0.8; background-size: cover; background-position: center;'> {% endcomment %}
        <div class="col-md-6 px-0">
            <h2 class="display-6 font-italic text-white">Make the Most of Our Lives</h2>
            <p class="lead my-3 text-white">sharing your memories and experiences</p>
        </div>
        <div class='p-sm-5 p-lg-5 p-xl-5'></div>
    </div>

    <div class="row mb-2">
        {% if ranks %}
        {% for rank in ranks %}
        <div class="col-md-6">
            <div class="row g-0 border rounded oberflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                <div class="col p-4 d-flex flex-column position-static">
                <strong class="d-inline-block mb-2 text-primary">
                    {% for tag in rank.tags.all %}
                        #{{ tag.name }}　 
                    {% endfor %}
                </strong>
                <h3 class="mb-0">{{ rank.title }}</h3>
                <div class="mb-1 text-muted">{{ rank.created_at|date:"Y-m-j" }}　
                    <div class="d-inline-block text-warning">
                        <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" class="bi bi-lightning-fill" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M11.251.068a.5.5 0 0 1 .227.58L9.677 6.5H13a.5.5 0 0 1 .364.843l-8 8.5a.5.5 0 0 1-.842-.49L6.323 9.5H3a.5.5 0 0 1-.364-.843l8-8.5a.5.5 0 0 1 .615-.09z"/>
                        </svg>
                        {{ rank.like_count }}
                    </div>
                </div>
                <p class="card-text mb-auto">{{ rank.text|truncatechars:130|linebreaks }}</p>
                <a href="{% url 'blog:article' rank.pk %}" class="stretched-link"></a>
                </div>
            </div>
        </div>    
        {% endfor %}    
        {% endif %}
    </div>

</div>

<main class="container">
    <div class="row">
        <div class="col-md-8">
        <h3 class="pb-2 mb-4" style="font-family: 'Raleway', sans-serif; font-size: 30px; border-bottom-style: groove; border-bottom-color: rgba(255, 255, 255, .6);">Experience</h3>




        {% if articles %}
        {% for article in articles %}
        <div class="blog-post">
                <h2 class="blog-post-title">{{ article.title }}</h2>
                <p class="blog-post-meta">{{ article.created_at|date:"Y-m-j" }}  by <a href="#">{{ article.author }}</a></p>
                <p>{{ article.text|slice:':150' }}...</p>
                <a href="{% url 'blog:article' article.id %}" class="">Read more...</a>
        </div>
        <hr>
        {% endfor %}
        {% endif %}





        {% include 'mysite/snippets/pagination.html' %}
        
        <nav class="blog-pagination">
            <a href="{% url 'blog:blog' %}" class="btn btn-outline-primary">Blog List</a>

        </nav>

        </div>

        {% include 'mysite/snippets/sidebar.html' %}

    </div>

</main>


{% endblock %}

templates/mysite/landing.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title>Starter Template - Materialize</title>

  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="css/style.css" type="text/css" rel="stylesheet" media="screen,projection"/>

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
            


</head>

<body>
  <nav class="light-blue lighten-1" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="#" class="brand-logo">Logo</a>
      <ul class="right hide-on-med-and-down">
        <li><a href="#">Navbar Link</a></li>
      </ul>

      <ul id="nav-mobile" class="sidenav">
        <li><a href="#">Navbar Link</a></li>
      </ul>
      <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    </div>
  </nav>
  <div class="section no-pad-bot" id="index-banner">
    <div class="container">
      <br><br>
      <h1 class="header center orange-text">Starter Template</h1>
      <div class="row center">
        <h5 class="header col s12 light">A modern responsive front-end framework based on Material Design</h5>
      </div>
      <div class="row center">
        <a href="http://materializecss.com/getting-started.html" id="download-button" class="btn-large waves-effect waves-light orange">Get Started</a>
      </div>
      <br><br>

    </div>
  </div>


  <div class="container">
    <div class="section">

      <!--   Icon Section   -->
      <div class="row">
        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center light-blue-text"><i class="material-icons">flash_on</i></h2>
            <h5 class="center">Speeds up development</h5>

            <p class="light">We did most of the heavy lifting for you to provide a default stylings that incorporate our custom components. Additionally, we refined animations and transitions to provide a smoother experience for developers.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center light-blue-text"><i class="material-icons">group</i></h2>
            <h5 class="center">User Experience Focused</h5>

            <p class="light">By utilizing elements and principles of Material Design, we were able to create a framework that incorporates components and animations that provide more feedback to users. Additionally, a single underlying responsive system across all platforms allow for a more unified user experience.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center light-blue-text"><i class="material-icons">settings</i></h2>
            <h5 class="center">Easy to work with</h5>

            <p class="light">We have provided detailed documentation as well as specific code examples to help new users get started. We are also always open to feedback and can answer any questions a user may have about Materialize.</p>
          </div>
        </div>
      </div>

    </div>
    <br><br>
  </div>

  <footer class="page-footer orange">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Company Bio</h5>
          <p class="grey-text text-lighten-4">We are a team of college students working on this project like it's our full time job. Any amount would help support and continue development on this project and is greatly appreciated.</p>


        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Settings</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Connect</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      Made by <a class="orange-text text-lighten-3" href="http://materializecss.com">Materialize</a>
      </div>
    </div>
  </footer>


  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="js/materialize.js"></script>
  <script src="js/init.js"></script>

  </body>
</html>

templates/mysite/mypage.html
{% extends 'mysite/base.html' %}
 
{% block content %}
 
<main class="container">
    <div class="row">
        <div class="col-md-8">
        <h3 class="pb-3 mb-4" style="font-family: 'Raleway', sans-serif; font-size: 30px; border-bottom-style: groove; border-bottom-color: rgba(255, 255, 255, .6);">
            MyPage
        </h3>
        {% if user.is_authenticated %}
        <div>
        <p><a href='{% url "blog:add" %}'>新規投稿はこちらから</a></p>
        <p><a href='{% url "blog:my_posts" %}'>あなたの投稿一覧</a></p>
        </div>
        <hr>
        {% endif %}
        <form class="row g-3" method="POST" enctype='multipart/form-data'>
            {% csrf_token %}


            {% include 'mysite/snippets/profile_image.html' %}
            

            <div class="col-12">
                <label class="form-label">Username（in public）</label>
                <input type="text" class="form-control" id="id_username" name="username" placeholder="Yamada Taro" value="{{ user.profile.username }}">
              </div>
 
              <div class="col-md-2">
                <label class="form-label">Country</label>
                <input type="text" class="form-control" id="id_country" name="country" value="{{ user.profile.country }}">
              </div>
              <div class="col-md-4">
                <label class="form-label">City</label>
                <input type='text' id="id_city" name="city" class="form-control" value="{{ user.profile.city }}">
              </div>
              <div class="col-md-6">
                <label class="form-label">Age</label>
                <input class="form-control" id="id_age" name="age" value="{{ user.profile.age }}">
              </div>
              
            <div class="col-12">
              <label class="form-label">Hobby</label>
              <input type="text" class="form-control" id="id_hobby" name="hobby" placeholder="Hobby" value="{{ user.profile.hobby }}">
            </div>
 
            <div class="col-12">
              <button type="submit" class="btn btn-success">Save</button>
            </div>

          </form>
 
        </div>
 
        {% include 'mysite/snippets/sidebar.html' %}
 
    </div>
</main>
 
 
{% endblock %}

templates/mysite/pay.html
{% extends 'mysite/base.html' %}

{% block content %}

<main class="container">
    <div class="row">
        <div class="col-md-8">
            <h3 class="pb-4 mb-4 font-italic border-bottom">Payment</h3>

            {% if charge %}
            <p>Payment amount: {{ charge.amount }}</p>
            <p>Brand: {{ charge.card.brand }}</p>
            <p>****-****-****-{{ charge.card.last4 }}</p>
            {% endif %}
            
            <form method="POST">
            {% csrf_token %}

                <script type='text/javascript' src='https://checkout.pay.jp' class="payjp-button" data-key='{{ public_key }}'>

                </script>

            </form>
        
        
        
        </div>

        {% include 'mysite/snippets/sidebar.html' %}

    </div>

</main>


{% endblock %}