blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'


urlpatterns = [
    # slug:pkとすることで、'localhost:8000/blog/~'の"~"に入ったものを変数pkとして使用できる
    # （slugの他、int=整数のみ, str=文字列のみがある）
    path("<int:pk>/", views.article, name="article"),
    path("tags/<slug:slug>/", views.tags, name="tags"),
    path("", views.blog, name="blog"),
    path('<slug:pk>/like/', views.like),
    path('<slug:pk>/fav/', views.add_favorite),
    path('add/', views.add_post, name='add'),
    path('edit/<int:pk>', views.edit_post, name='edit'),
    path('delete/<int:pk>/', views.delete_post, name="delete"),
    path('my_posts/', views.my_posts, name='my_posts'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', include('account.urls')),
]
# + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import os
from account.models import Profile

class Tag(models.Model):
    slug = models.CharField(    # slug: 半角文字
        primary_key=True,   # slug = id として扱える
        unique=True,
        max_length=20,
    )
    name = models.CharField(
        unique=True,
        max_length=20,
    )
    class Meta:
        ordering = ("slug", ) # slugで昇順ソート

    def __str__(self):
        return self.slug


def upload_blogimage_to(instance, filename):
    return os.path.join('image', 'blog', filename)

class Article(models.Model):
    title = models.CharField(
        max_length=30, 
        default="",
    )
    text = models.TextField(
        default="",
    )
    author = models.ForeignKey(
        Profile,
        on_delete=models.CASCADE,
        default='1'
    )
    created_at = models.DateField(
        auto_now_add=True, 
    )
    updated_at = models.DateField(
        auto_now=True, 
    )
    like_count = models.IntegerField(
       default=0,
    )
    tags = models.ManyToManyField(
        Tag,
        blank=True,
    )
    image = models.ImageField(
        upload_to = upload_blogimage_to,
        default="",
        blank=True,
    )
    favorite = models.ManyToManyField(
        Profile,
        related_name='favorite_by',
        blank=True,
    )
    is_published = models.BooleanField(
        default=False,
    )

    def __str__(self):
        return self.title


class Comment(models.Model):

    comment = models.TextField(
        default="", 
        max_length=500, 
    )
    created_at = models.DateField(
        auto_now_add=True, 
    )
    user = models.ForeignKey(
        Profile, 
        on_delete=models.CASCADE    # Userがいなくなったら、そのコメントは削除
    )    
    article = models.ForeignKey(
        Article, 
        on_delete=models.CASCADE    # 記事がなくなったら、そのコメントは削除
    )

blog/forms.py
from django import forms
from .models import Comment, Article

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = (
            'comment',   # templateで送信される項目（textarea name="comment"）であり、modelsのフィールド名
        )

class PostForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = (
            'title', 'text', 'author', 'tags', 'image', 'is_published', 
        )
        labels = {
            'title': 'タイトル',
            'text':'本文', 
            'author': '筆者', 
            'tags': 'タグ', 
            'image': '画像', 
            'is_published': '公開',
        }

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(PostForm, self).__init__(*args, **kwargs)
        for field in self.base_fields.values():
            field.widget.attrs["class"] = "form-control"
        self.fields['author'].initial = self.user
        self.fields['is_published'] = forms.BooleanField(label='公開', required=False)

blog/views.py
from django.shortcuts import render, redirect
from .models import Article, Comment, Tag
from django.core.paginator import Paginator
from .forms import CommentForm, PostForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages


def blog(request):
    articles = Article.objects.filter(is_published=True).order_by('-created_at')
    paginator = Paginator(articles, 3)  # 公開3つ/ページ
    page_number = request.GET.get('page')   # urlのパス名に'page'があれば、キー（page=1の1部分）を取得
    context = {
        'page_title': 'Blog List',
        'page_article': paginator.get_page(page_number),
        'page_number': page_number,
    }
    return render(request,
        'blog/blogs.html',
        context
    )

# def draft(request):
#     articles = Article.objects.filter(is_published=False).order_by("-created_at")
#     paginator = Paginator(articles, 3)  # 公開3つ/ページ
#     page_number = request.GET.get('page')   # urlのパス名に'page'があれば、キー（page=1の1部分）を取得
#     context = {
#         'page_title': 'Blog List',
#         'page_published_article': paginator.get_page(page_number),
#         'page_number': page_number,
#     }
#     return render(request,
#         'blog/blogs.html',
#         context
#     )


def article(request, pk):
    article = Article.objects.get(pk=pk)
    if request.method == 'POST':
        if request.POST.get('like_count', None):
            article.like_count += 1
            article.save()
        else:
            form = CommentForm(request.POST)
            if form.is_valid():
                comment = form.save(commit=False)   # DBには反映しないが、変数commentに渡す(CommentモデルのcommentはCommentFormのfieldsで指定した通り、ここに含まれる)
                # 以下、CommentFormで指定しなかったfieldsの定義
                comment.user = request.user.profile         # Commentモデルのuserは、その時のユーザー(formをPOSTしたログインユーザー)
                comment.article = article           # 上で指定したpkのarticle
                comment.save()

    comments = Comment.objects.filter(article=article)  # Commentモデルのarticleフィールド=指定したpkのarticleのコメント
    context = {
        'article': article,
        'comments': comments,
        'my_post': article.author.user == request.user, # 自分の投稿であればTrue, そうでなければfalse
    }

    return render(request,
        'blog/article.html',
        context
    )


def tags(request, slug):
    tag = Tag.objects.get(slug=slug)
    articles = tag.article_set.filter(is_published=True)    # tagを参照しているArticle
    # ----- index()関数の使い回し（一部変更） -----
    paginator = Paginator(articles, 10)  # 10こ/ページ
    page_number = request.GET.get('page')   # urlのパス名に'page'があれば、キー（page=1の1部分）を取得
    context = {
        'page_title' : f'# {slug}',
        'page_article': paginator.get_page(page_number),
        'page_number': page_number,
    }
    return render(request,
        'blog/blogs.html',
        context
    )


from django.views.decorators.csrf import ensure_csrf_cookie
from django.http import JsonResponse

@ensure_csrf_cookie # csrf_tokenがないとPOST送信されないため
def like(request, pk):
    d = {'message': 'error'}
    if request.method == 'POST':
        article = Article.objects.get(pk=pk)
        article.like_count += 1
        article.save()

        d['message'] = 'success'
    return JsonResponse(d)      # templateで返すのではなく、Jsonで返す



# articleをお気に入り登録する
@ensure_csrf_cookie
def add_favorite(request, pk):
    article = Article.objects.get(pk=pk)
    profile = request.user.profile

    d = {'message': 'error'}
    if request.method == 'POST':
        if profile in article.favorite.all():
            article.favorite.remove(profile)
        else:
            article.favorite.add(profile)
        d['message'] = 'success'

    return JsonResponse(d)


def add_post(request):
    kwargs = {'user': request.user.profile.username}
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, **kwargs)
        if form.is_valid():
            form.save(commit=False)
            form.author = request.user.profile
            form.save()
            messages.success(request, f'「新しい投稿が完了しました。')
            return redirect('blog:blog')
    else:
        form = PostForm(**kwargs)
        return render(request,
            'mysite/add_post.html',
            context = {
                'form': form,
            }
        )

def my_posts(request):
    articles = Article.objects.filter(author=request.user.profile)
    published = articles.filter(is_published=True)
    draft = articles.filter(is_published=False)
    return render(request,
        'blog/blogs.html',
        context = {
            'page_article': articles,
            'published': published, 
            'draft': draft,
        }
    )

def edit_post(request, pk):
    article = Article.objects.get(pk=pk)
    kwargs = {'user': request.user.profile.username}

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=article, **kwargs)
        if form.is_valid():
            form.save(commit=False)
            form.author = request.user.profile
            form.save()
            messages.success(request, f'「{article.title}」を更新しました。')
            return redirect('blog:my_posts')
    else:
        form = PostForm(instance=article, **kwargs)
        return render(request,
            'mysite/add_post.html',
            context = {
                'form': form,
                'article': article
            }
        )

def delete_post(request, pk):
    article = Article.objects.get(pk=pk)
    
    if request.method == "POST":
        article.delete()
        messages.info(request, f'「{article.title}」を削除しました。')
    return redirect('blog:my_posts')

    
    

templates/blog/article.html
{% extends 'mysite/base.html' %}
{% load cache %}
{% load static %}

{% block content %}

<main class="container">
    <div class="row">
        <div class="col-md-8">

        {% comment %} {% cache 86400 article article.id %} {% endcomment %}
            <div class="d-flex justify-content-between">
            <h4 class="font-italic display-6">{{ article.title }}</h4>

            {% if my_post %}
            <div class="d-flex me-4">
                <p><a class='btn btn-md btn-outline-secondary mb-2 px-3' href='{% url "blog:edit" article.id %}'> Edit </a></p>
                <form method="POST" action='{% url "blog:delete" article.id %}'>{% csrf_token %}<input class='btn btn-md btn-outline-danger mx-2 mb-2 px-2' type="submit" value="Delete"></form>
            </div>
            {% endif %}

            </div>
            <p class="small text-muted text-right">{{ article.created_at|date:"Y-m-j" }}  by <a href="#">{{ article.author }}</a></p>

            {% if article.image %}
                <img src='{{ article.image.url }}' style='max-width:100%; max-height:100%;'>
            
                {% comment %} <img src='https://storage.googleapis.com/django-mysite/{{article.image}}' style='max-width:100%; max-height:100%;'> {% endcomment %}
            {% endif %}

            <div class="my-5">{{ article.text|linebreaks }}</div>
        {% comment %} {% endcache %} {% endcomment %}



        <div>
        {% include 'mysite/snippets/like_count.html' %}

        {% if user.is_authenticated %}
            {% include 'mysite/snippets/add_favorite.html' %}
        {% endif %}

        {% include 'mysite/snippets/tag.html' %}
        </div>

        <hr class="my-4">
        {% include 'mysite/snippets/comment.html' %}


        </div>
    
        {% include 'mysite/snippets/sidebar.html' %}

    </div>

</main>




{% endblock %}

templates/blog/blogs.html
{% extends 'mysite/base.html' %}

{% block content %}

<main class="container">
    <div class="row">
        <div class="col-md-8">

        {% if 'my' not in request.path %}
        <h3 class="pb-3 mb-4" style="font-family: 'Raleway', sans-serif; font-size: 30px; border-bottom-style: groove; border-bottom-color: rgba(255, 255, 255, .6); ">{{ page_title }}</h3>

            {% for article in page_article %}
            <div class="blog-post">
                <div class="d-flex">
                <h2 class="blog-post-title">{{ article.title }}</h2>

                {% if 'my' in request.path %}
                    <div class="d-flex justify-content-end mx-4">
                        <a class='btn btn-md btn-outline-secondary mb-2' href='{% url "blog:edit" article.id %}'>Edit</a>
                        <form method="POST" action='{% url "blog:delete" article.id %}'>{% csrf_token %}<input class='btn btn-md btn-outline-danger mx-2 mb-2' type="submit" value="Delete"></form>
                    </div>
                {% endif %}
                </div>

                <p class="blog-post-meta">{{ article.created_at|date:"Y-m-j" }}  by <a href="#">{{ article.author }}</a></p>

                <p>{{ article.text|truncatechars:200 }}</p>
                <a href="{% url 'blog:article' article.id %}" class="">Read more...</a>
            </div>  
            <hr>
            {% endfor %}

            {% else %}
            
            {% if published %}
            <h3 class="pb-3 mb-4" style="font-family: 'Raleway', sans-serif; font-size: 30px; border-bottom-style: groove; border-bottom-color: rgba(255, 255, 255, .6); ">Published</h3>

                {% for article in published %}
                <div class="blog-post">
                    <div class="d-flex">
                    <h2 class="blog-post-title">{{ article.title }}</h2>

                    {% if 'my' in request.path %}
                        <div class="d-flex justify-content-end mx-4">
                            <a class='btn btn-md btn-outline-secondary mb-2' href='{% url "blog:edit" article.id %}'>Edit</a>
                            <form method="POST" action='{% url "blog:delete" article.id %}'>{% csrf_token %}<input class='btn btn-md btn-outline-danger mx-2 mb-2' type="submit" value="Delete"></form>
                        </div>
                    {% endif %}
                    </div>

                    <p class="blog-post-meta">{{ article.created_at|date:"Y-m-j" }}  by <a href="#">{{ article.author }}</a></p>

                    <p>{{ article.text|truncatechars:200 }}</p>
                    <a href="{% url 'blog:article' article.id %}" class="">Read more...</a>
                </div>  
                <hr>
                {% endfor %}
            {% endif %}

                <br><br>
                {% if draft %}
                <h3 class="pb-3 mb-4" style="font-family: 'Raleway', sans-serif; font-size: 30px; border-bottom-style: groove; border-bottom-color: rgba(255, 255, 255, .6); ">Draft</h3>

                    {% for article in draft %}
                    <div class="blog-post">
                        <div class="d-flex">
                        <h2 class="blog-post-title">{{ article.title }}</h2>

                        {% if 'my' in request.path %}
                            <div class="d-flex justify-content-end mx-4">
                                <a class='btn btn-md btn-outline-secondary mb-2' href='{% url "blog:edit" article.id %}'>Edit</a>
                                <form method="POST" action='{% url "blog:delete" article.id %}'>{% csrf_token %}<input class='btn btn-md btn-outline-danger mx-2 mb-2' type="submit" value="Delete"></form>
                            </div>
                        {% endif %}
                        </div>

                        <p class="blog-post-meta">{{ article.created_at|date:"Y-m-j" }}  by <a href="#">{{ article.author }}</a></p>

                        <p>{{ article.text|truncatechars:200 }}</p>
                        <a href="{% url 'blog:article' article.id %}" class="">Read more...</a>
                    </div>  
                    <hr>
                    {% endfor %}

                {% endif %}
            {% endif %}


        {% include 'mysite/snippets/pagination.html' %}


        </div>
    
        {% include 'mysite/snippets/sidebar.html' %}

    </div>

</main>




{% endblock %}