account/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

app_name = 'mysite'


urlpatterns = [
    
    path('', views.index, name='home'),
    # path('landing/', views.landing, ),  # Materializeを使用したトップページ

    path('login/', views.Login.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),

    path('mypage/', views.MyPageView.as_view(), name='mypage'),
    path('favorite/', views.favorite, name='favorite'),
    path('contact/', views.ContactView.as_view(), name='contact'),

    path('about/', views.about, name='about'),

]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'


urlpatterns = [
    # slug:pkとすることで、'localhost:8000/blog/~'の"~"に入ったものを変数pkとして使用できる
    # （slugの他、int=整数のみ, str=文字列のみがある）
    path("<int:pk>/", views.article, name="article"),
    path("tags/<slug:slug>/", views.tags, name="tags"),
    path("", views.blog, name="blog"),
    path('<slug:pk>/like/', views.like),
    path('<slug:pk>/fav/', views.add_favorite),
    path('add/', views.add_post, name='add'),
    path('edit/<int:pk>', views.edit_post, name='edit'),
    path('delete/<int:pk>/', views.delete_post, name="delete"),
    path('my_posts/', views.my_posts, name='my_posts'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', include('account.urls')),
]
# + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import os
from account.models import Profile

class Tag(models.Model):
    slug = models.CharField(    # slug: 半角文字
        primary_key=True,   # slug = id として扱える
        unique=True,
        max_length=20,
    )
    name = models.CharField(
        unique=True,
        max_length=20,
    )
    class Meta:
        ordering = ("slug", ) # slugで昇順ソート

    def __str__(self):
        return self.slug


def upload_blogimage_to(instance, filename):
    return os.path.join('image', 'blog', filename)

class Article(models.Model):
    title = models.CharField(
        max_length=30, 
        default="",
    )
    text = models.TextField(
        default="",
    )
    author = models.ForeignKey(
        Profile,
        on_delete=models.CASCADE,
        default='1'
    )
    created_at = models.DateField(
        auto_now_add=True, 
    )
    updated_at = models.DateField(
        auto_now=True, 
    )
    like_count = models.IntegerField(
       default=0,
    )
    tags = models.ManyToManyField(
        Tag,
        blank=True,
    )
    image = models.ImageField(
        upload_to = upload_blogimage_to,
        default="",
        blank=True,
    )
    favorite = models.ManyToManyField(
        Profile,
        related_name='favorite_by',
        blank=True,
    )
    is_published = models.BooleanField(
        default=False,
    )

    def __str__(self):
        return self.title


class Comment(models.Model):

    comment = models.TextField(
        default="", 
        max_length=500, 
    )
    created_at = models.DateField(
        auto_now_add=True, 
    )
    user = models.ForeignKey(
        Profile, 
        on_delete=models.CASCADE    # Userがいなくなったら、そのコメントは削除
    )    
    article = models.ForeignKey(
        Article, 
        on_delete=models.CASCADE    # 記事がなくなったら、そのコメントは削除
    )

templates/mysite/snippets/add_favorite.html
<div class='d-inline my-1'>
    <button type='button' id='fav_btn' class='btn btn-sm btn-outline-danger' style='margin: 2px;'>
        <div id='fav_status' style='display: inline-block;'>

            {% if article in user.profile.favorite_by.all %}
            <span id="added">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star-fill" viewBox="0 0 16 16">
                    <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                </svg>
            </span>
            {% else %}
            <span id="removed">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star" viewBox="0 0 16 16">
                    <path d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.522-3.356c.33-.314.16-.888-.282-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767-3.686 1.894.694-3.957a.565.565 0 0 0-.163-.505L1.71 6.745l4.052-.576a.525.525 0 0 0 .393-.288L8 2.223l1.847 3.658a.525.525 0 0 0 .393.288l4.052.575-2.906 2.77a.565.565 0 0 0-.163.506l.694 3.957-3.686-1.894a.503.503 0 0 0-.461 0z"/>
                </svg>
            </span>
            {% endif %}
            
        </div> Fav

    </button>
</div>


<script>
    window.addEventListener('DOMContentLoaded', (event) => {
        
        const favBtn = document.getElementById('fav_btn');
        favBtn.addEventListener('click', (event) => {
            const url = 'fav/';
            const csrfToken = getCookie('csrftoken');
            let data = {};

            fetch(url, {
                method: 'POST',
                credentials: 'same-origin',
                headers: {
                    'Content-Type': 'application/json',
                    'X-Requested-With': 'XMLHttpRequest',
                    'X-CSRFToken': csrfToken,
                },
                body: JSON.stringify(data)

            })
            .then(Response => Response.json())
            
            .then(data => {
                console.log(data);
                if (data['message'] === 'success') {
                    const favStatus = document.getElementById('fav_status');
                    const originalStatus = (favStatus.firstElementChild.id);
                    if (originalStatus === 'added') {
                        favStatus.innerHTML = ('<span id="removed"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star" viewBox="0 0 16 16"><path d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.522-3.356c.33-.314.16-.888-.282-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767-3.686 1.894.694-3.957a.565.565 0 0 0-.163-.505L1.71 6.745l4.052-.576a.525.525 0 0 0 .393-.288L8 2.223l1.847 3.658a.525.525 0 0 0 .393.288l4.052.575-2.906 2.77a.565.565 0 0 0-.163.506l.694 3.957-3.686-1.894a.503.503 0 0 0-.461 0z"/></svg></span>');
                    } else {
                        favStatus.innerHTML = ('<span id="added"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star-fill" viewBox="0 0 16 16"><path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/></svg></span>');                        
                    }
                }
            })
            
            // 通信がうまくいかなかった等のエラーが発生した場合
            .catch((error) => {
                console.log(error);
            });

        }, false);
    }, false);

function getCookie(name) {
    if (document.cookie && document.cookie !== "") {
        for (const cookie of document.cookie.split(';')) {
            const [key, value] = cookie.trim().split('=');
            if (key === name) {
                return decodeURIComponent(value);
            }
        }
    }
    return null;
}


</script>

templates/mysite/snippets/comment.html
<div>
    <h3 class="h6">Comment</h3>
    <div class="list-group">
        {% for comment in comments %}
        <a class="list-group-item list-group-item-action p-3 rounded-0">
            <p class="m-0"><small>{{ comment.comment }}</small></p>
            <p class="m-0"><small>
                by {{ comment.user.username }}　
                {{ comment.created_at|date:'Y-m-j' }}
            </small></p>
        </a>
        {% endfor %}
    </div>

    {% if user.is_authenticated %}
    <form method="POST" class="my-4">
    {% csrf_token %}
        <div class="mb-2">
            <label>Comment Post</label>
            <textarea name="comment" class="rounded-0 bg-light form-control" rows="3"></textarea>
        </div>
        <div class="text-right">
            <button class="btn btn-sm btn-outline-success" type="submit">
                Post
            </button>
        </div>
    </form>
   
    {% else %}
    <p class="my-4">
        To post a comment <a href="{% url 'mysite:login' %}">Login</a> Please!!
    </p>

    {% endif %}


</div>

templates/mysite/snippets/footer.html
    <footer class="border-top py-5 text-center bg-light mt-4">
        <p>
            <a href="{% url 'mysite:home' %}">Back to Top</a>
        </p>

    </footer>

templates/mysite/snippets/grecaptcha.html
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
 
    <div class="g-recaptcha"
         data-sitekey="{{ grecaptcha_sitekey }}"
         data-callback="verifyCallback">    
    </div>

    <script>
        // コールバック関数 recaptchaにチェックしないと、送信ボタンを押せないようJSで実装
        function verifyCallback(response) {
            // submitのdisabled属性を解除
            document.getElementById('submit').disabled = false;
        }
    </script>

templates/mysite/snippets/head.html
    
    <!-- Global site tag (gtag.js) - Google Analytics -->
    {% comment %} <script async src="https://www.googletagmanager.com/gtag/js?id=G-98183ZTBV4"></script>
    <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-98183ZTBV4');
    </script> {% endcomment %}
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@1,700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@1,600&display=swap" rel="stylesheet">


    <title>Find Awesome</title>

templates/mysite/snippets/header.html
<div class="container">
    <header class="py-3">
        <div class="row flex-nowrap justify-content-center align-items-center">
        <div class="col-4 text-center">
            <h1 class="display-6" style="font-family: 'Raleway', sans-serif;"><b><a href="{% url 'mysite:home' %}" class="text-decoration-none link-dark">Find Awesome</a></B></h1>
        </div>
        </div>
    </header>

    <div class="py-1 mb-2">
        <nav class="nav d-flex justify-content-between">
            <a class="p-2 link-secondary" href="{% url 'mysite:about' %}">About</a>
            <a class="p-2 link-secondary" href="{% url 'blog:blog' %}">Blog</a>
            <a class="p-2 link-secondary" href="{% url 'mysite:contact' %}">Contact</a>
            {% if user.is_authenticated %}
                <div class='p-2'>
                    <a class="me-2 link-secondary" href="{% url 'mysite:logout' %}">Logout</a>
                    <a class="ms-2 link-secondary" href="{% url 'mysite:mypage' %}">MyPage</a>
                </div>
            {% else %}
                <div class=''>
                    <a class="mx-2 link-secondary" href="{% url 'mysite:login' %}">Login</a>
                    <a class="btn btn-outline-info" href="{% url 'mysite:signup' %}">SignUp</a>
                </div>
            {% endif %}
        </nav>
    </div>
</div>

templates/mysite/snippets/like_count.html
<!--
    <form method="POST" class='d-inline'>
    {% csrf_token %}
        <input type="hidden" name="like_count" value="true">
        <button type="submit" class="btn btn-sm btn-outline-warning">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-lightning-fill" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M11.251.068a.5.5 0 0 1 .227.58L9.677 6.5H13a.5.5 0 0 1 .364.843l-8 8.5a.5.5 0 0 1-.842-.49L6.323 9.5H3a.5.5 0 0 1-.364-.843l8-8.5a.5.5 0 0 1 .615-.09z"/>
            </svg>
            {{ article.like_count }} Like
        </button>

    </form>
-->

<div class='d-inline my-1'>
    <button type='button' id='like_btn' class='btn btn-sm btn-outline-warning' style='margin: 2px;'>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-lightning-fill" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M11.251.068a.5.5 0 0 1 .227.58L9.677 6.5H13a.5.5 0 0 1 .364.843l-8 8.5a.5.5 0 0 1-.842-.49L6.323 9.5H3a.5.5 0 0 1-.364-.843l8-8.5a.5.5 0 0 1 .615-.09z"/>
        </svg>
        <span id='like_count'>{{ article.like_count }}</span> Like
    </button>

</div>


<script>
    // ページ内容がオブジェクトとして読み込まれた(=DOMContentListener)時、イベントとして検知する(=addEventListener)
    window.addEventListener('DOMContentLoaded', (event) => {    // 要素.addEventListener(イベント, 関数, オプション);

        const likeBtn = document.getElementById('like_btn');
        likeBtn.addEventListener('click', (event) => {
            // 送信先URL
            const url = '/blog/{{article.id}}/like/';
            // csrftokenの取得（↓getCookie関数より）
            const csrfToken = getCookie('csrftoken');
            // 送信したいデータがある場合
            let data = {};

            // 送信(viewにdataを渡す)
            fetch(url, {
                method: 'POST',
                credentials: 'same-origin',
                headers: {
                    'Content-type': 'application/json',
                    'X-Requested-With': 'XMLHttpRequest',
                    'X-CSRFToken': csrfToken,
                },
                body: JSON.stringify(data),
            })
            // viewから返ってきたJSONResponseを受け取る
            .then(Response => Response.json())
            .then(data => {
                console.log(data);
                if (data['message'] === 'success') {
                    var likeCount = document.getElementById('like_count');
                    likeCount.innerText = (Number(likeCount.innerText)+1).toString();   // 文字列をnumberにして+1した上で、再度文字列に
                }
            })
            // 通信がうまくいかなかった等のエラーが発生した場合
            .catch((error) => {
                console.log(error);
            });

        }, false);
    }, false);


function getCookie(name) {
    if (document.cookie && document.cookie !== "") {
        for (const cookie of document.cookie.split(';')) {
            const [key, value] = cookie.trim().split('=');
            if (key === name) {
                return decodeURIComponent(value);
            }
        }
    }
    return null;
}

</script>

templates/mysite/snippets/messages.html
{% for message in messages %}
<nav class="py-2 {{ message.tags }}">
    <div class="container">
        {{ message }}
    </div>
</nav>
{% endfor %}

templates/mysite/snippets/pagination.html
<nav class="blog-pagination">

    <div class="pagination">

        <span class="step-links">

            {% if page_article.has_previous %}
                <a class="btn btn-outline-primary" href="?page=1">&laquo; first</a>
                <a class="btn btn-outline-primary" href="?page={{ page_article.previous_page_number }}">previous</a>
            {% endif %}

            {% comment %} <span class="current">
                Page {{ page_article.number }} of {{ page_article.paginator.num_pages }}.
            </span> {% endcomment %}

            {% if page_article.has_next %}
                <a class="btn btn-outline-primary" href="?page={{ page_article.next_page_number }}">next</a>
                <a class="btn btn-outline-primary" href="?page={{ page_article.paginator.num_pages}}">last &raquo;</a>
            {% endif %}

        </span>
    </div>
</nav>

templates/mysite/snippets/profile_image.html
<label>Profile Image</label>

<label id=="id_image_label" for='id_image'>

    <!-- デフォルト upload -->
    
    <div id='no_image' class="{% if user.profile.image != '' %}d-none{% endif %} border rounded-circle bg-light" style="width:150px; height:150px;">

        <div class="m-auto p-5">
            <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="auto" fill="currentColor" class="bi bi-cloud-upload" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M4.406 1.342A5.53 5.53 0 0 1 8 0c2.69 0 4.923 2 5.166 4.579C14.758 4.804 16 6.137 16 7.773 16 9.569 14.502 11 12.687 11H10a.5.5 0 0 1 0-1h2.688C13.979 10 15 8.988 15 7.773c0-1.216-1.02-2.228-2.313-2.228h-.5v-.5C12.188 2.825 10.328 1 8 1a4.53 4.53 0 0 0-2.941 1.1c-.757.652-1.153 1.438-1.153 2.055v.448l-.445.049C2.064 4.805 1 5.952 1 7.318 1 8.785 2.23 10 3.781 10H6a.5.5 0 0 1 0 1H3.781C1.708 11 0 9.366 0 7.318c0-1.763 1.266-3.223 2.942-3.593.143-.863.698-1.723 1.464-2.383z"/>
                <path fill-rule="evenodd" d="M7.646 4.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1-.708.708L8.5 5.707V14.5a.5.5 0 0 1-1 0V5.707L5.354 7.854a.5.5 0 1 1-.708-.708l3-3z"/>
            </svg>
        </div>

    </div>

    <!-- 画像がある場合 -->
    {% if user.profile.image %}
    <img id='image_preview' src='{{user.profile.image.url}}' class='{% if user.profile.image == '' %}d-none{% endif %} border rounded-circle' style='width: 150px; height: 150px; object-fit: cover;'>
    {% endif %}
</label>

<!-- input -->
<div class="d-none">
    <input type='file' accept='image/*' id='id_image' name='image' onchange="previewImage(this)">
</div>

<!-- プレビュー script -->
<script>
    function previewImage(elem) {
        var fileReader = new FileReader();
        fileReader.onload = (function(){
            document.getElementById('image_preview').classList.remove('d-none');
            document.getElementById('no_image').classList.add('d-none');

            document.getElementById('image_preview').src = fileReader.result;
        });
        fileReader.readAsDataURL(elem.files[0]);
    }


</script>

templates/mysite/snippets/sidebar.html
{% load static %}
{% load cache %}

{% comment %} {% cache 3600 sidebar %} {% endcomment %}
<aside class="col-md-4">
    <div class="p-4 mb-3 bg-light rounded" style='width:100%; align-items: center;'>
        <div class="" style='display: inline-block;'>

            {% if user.is_authenticated %}
                <a href="{% url 'mysite:mypage' %}" class="text-decoration-none link-dark"><h4 class="font-italic"> {{ user.profile.username }}</h4></a>

                <a href="{% url 'mysite:favorite' %}" style='display:inlne-block;'>
                    <button type="button" class="btn btn-outline-danger my-2">
                        <svg xmlns="http://www.w3.org/2000/svg" width="10" height="10" fill="currentColor" class="bi bi-star-fill" viewBox="0 0 16 16">
                            <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"></path>
                        </svg>
                        Fav List
                    </button>
                </a>

            {% else %}
                <h4>User</h4>
                <p>Let's find something new!!</p>
            {% endif %}
        </div>

            {% if user.is_authenticated %}
                {% if user.profile.image %}
                    <img src='{{ user.profile.image.url }}' class='m-2' style='border-radius: 50%; max-width: 70%; width: 175px;'>
                {% else %}
                    <img src='{% static "mysite/user.png" %}' class="m-2" style="border-radius: 50%; max-width: 70%; width: 85px;">
                {% endif %}
            {% else %}
                <img src='{% static "mysite/user.png" %}' class="m-2" style="border-radius: 50%; max-width: 70%; width: 85px;">
            {% endif %}

    </div>


    <figure class="figure">
        <img src="{% static 'mysite/image01.jpg' %}" class="figure-img img-fluid rounded">
        <figcaption class="figure-caption text-center font-italic small">The places you'll go</figcaption>
    </figure>

    <figure class="figure">
        <img src="{% static 'mysite/image02.jpg' %}" class="figure-img img-fluid rounded">
        <figcaption class="figure-caption text-center font-italic small">Wherever you go becomes a part of you somehow</figcaption>
    </figure>

</aside>
{% comment %} {% endcache %} {% endcomment %}

templates/mysite/snippets/tag.html
{% for tag in article.tags.all %}

<a href='{% url 'blog:tags' tag.slug %}' class='btn btn-sm btn-outline-secondary' style='margin: 2px;'>
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-tag-fill" viewBox="0 0 16 16">
    <path d="M2 1a1 1 0 0 0-1 1v4.586a1 1 0 0 0 .293.707l7 7a1 1 0 0 0 1.414 0l4.586-4.586a1 1 0 0 0 0-1.414l-7-7A1 1 0 0 0 6.586 1H2zm4 3.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"/>
    </svg>
    {{ tag.name }}
</a>

{% endfor %}